In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\dell\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
## Creating series using tuple
t=(10,11,12,15)
d=pd.Series(t)
d

0    10
1    11
2    12
3    15
dtype: int64

In [5]:
type(d)

pandas.core.series.Series

In [6]:
##  creating series using list
l1=[45,78,56,445,78]
e=pd.Series(l1)
e

0     45
1     78
2     56
3    445
4     78
dtype: int64

In [8]:
## Creating series with array
import numpy as np
arr=np.array([1,2,3,4])
d1=pd.Series(arr)
type(d1)
d1

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
## Using dictionary
d={'a':1,'b':2,'c':3,'d':4}
d

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [10]:
d['b']

2

In [12]:
b=pd.Series(d)
b

a    1
b    2
c    3
d    4
dtype: int64

In [13]:
b.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [14]:
b.values

array([1, 2, 3, 4])

In [15]:
b['c'] #index access the value

np.int64(3)

In [16]:
import numpy as np
## Slicing operation
c=pd.Series(np.arange(10))
c

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [17]:
c[1:5] # accessing the series using slicing

1    1
2    2
3    3
4    4
dtype: int64

In [18]:
c[c>5] # Filtering

6    6
7    7
8    8
9    9
dtype: int64

In [19]:
odd=pd.Series([1,3,5,7])
even=pd.Series([2,4,6,8])
multi_od_ev=odd.multiply(even)
multi_od_ev

0     2
1    12
2    30
3    56
dtype: int64

In [20]:
add=odd+even
add

0     3
1     7
2    11
3    15
dtype: int64

In [21]:
sub=odd-even
sub

0   -1
1   -1
2   -1
3   -1
dtype: int64

In [22]:
div=odd/even
div

0    0.500000
1    0.750000
2    0.833333
3    0.875000
dtype: float64

In [23]:
series=pd.Series(data=[1,2,3,4,5,6],index=['a','b','c','d','e','f'])
series

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [24]:
df=['python','Statistics','MLA','SQL']
df_sub=pd.DataFrame(df)  # column name default takes "0"
df_sub

            0
0      python
1  Statistics
2         MLA
3         SQL

In [25]:
# dataframe using nested list
data=[['abc',1],['def',2],['ghi',3],['hij'],['klm','5']]
df_data=pd.DataFrame(data)
df_data

     0     1
0  abc     1
1  def     2
2  ghi     3
3  hij  None
4  klm     5

In [26]:
d=pd.DataFrame(data=data,columns=['A','B'],index=['A','B','C','D','E']) # changing the index
d

     A     B
A  abc     1
B  def     2
C  ghi     3
D  hij  None
E  klm     5

In [27]:
d=pd.DataFrame(data=data,columns=['A','B'],index=['A','B','C','D','E']) # changing the index
d

     A     B
A  abc     1
B  def     2
C  ghi     3
D  hij  None
E  klm     5

In [29]:
## dataframe using dictonary
dit={'name':['a','b','c','d','e','f'],'age':[45,12,48,25,12,56]}
df_dit=pd.DataFrame(dit)
df_dit

  name  age
0    a   45
1    b   12
2    c   48
3    d   25
4    e   12
5    f   56

In [30]:
df_dit.columns

Index(['name', 'age'], dtype='object')

In [31]:
df_dit.columns=['Candidate','Age_in_years']  
df_dit

  Candidate  Age_in_years
0         a            45
1         b            12
2         c            48
3         d            25
4         e            12
5         f            56

In [32]:
df_dit.rename({'Age_in_years':"Age"},axis=1,inplace=True) # changing the column name
df_dit

  Candidate  Age
0         a   45
1         b   12
2         c   48
3         d   25
4         e   12
5         f   56

In [33]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [34]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [35]:
df1=sns.load_dataset('titanic')
df1

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [36]:
df=pd.read_csv('train.xls')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [37]:
type(df1)

pandas.core.frame.DataFrame

In [38]:
df1.head() # display first 5 rows

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [39]:
df1.tail() # display last 5 rows

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [40]:
df1.shape  # shape of dataframe

(891, 15)

In [41]:
df1.dtypes # datatype of each column

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [42]:
df1.info() # information of dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [43]:
df1.columns # checking the column names

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [44]:
df1.describe() # summary of dataframe

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [45]:
df1.describe(include='O') # it will give the summary of objective type

         sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

In [46]:
df1['age'] # accessing the single column

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [47]:
df1[['age','sex','embarked','embark_town']] # accessing the multiple columns

      age     sex embarked  embark_town
0    22.0    male        S  Southampton
1    38.0  female        C    Cherbourg
2    26.0  female        S  Southampton
3    35.0  female        S  Southampton
4    35.0    male        S  Southampton
..    ...     ...      ...          ...
886  27.0    male        S  Southampton
887  19.0  female        S  Southampton
888   NaN  female        S  Southampton
889  26.0    male        C    Cherbourg
890  32.0    male        Q   Queenstown

[891 rows x 4 columns]

In [48]:
# iloc
df1.iloc[0:6] # access the first row with all the columns

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True

In [49]:
df.iloc[0:10,0:2]

   PassengerId  Survived
0            1         0
1            2         1
2            3         1
3            4         1
4            5         0
5            6         0
6            7         0
7            8         0
8            9         1
9           10         1

In [50]:
a=df1.loc[0:5][['class','age']]
a

   class   age
0  Third  22.0
1  First  38.0
2  Third  26.0
3  First  35.0
4  Third  35.0
5  Third   NaN

In [51]:
df1.loc[df1['age']>70]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [52]:
len(df1.loc[df1['age']>70])

5

In [53]:
df1.loc[df1['age']==70]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
672,0,2,male,70.0,0,0,10.5,S,Second,man,True,NaN,Southampton,no,True
745,0,1,male,70.0,1,1,71.0,S,First,man,True,B,Southampton,no,False

In [54]:
df1.loc[(df1['sex']=='male') & (df1['age']>70)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [55]:
#number of females in first class --task
df1.loc[(df1['sex']=='female') & (df1['class']=='First')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
52,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [56]:
#number of females that survived the titanic crash in first class
df1.loc[(df1['sex']=='female') & (df1['class']=='First') & (df1['survived']==0)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
177,0,1,female,50.0,0,0,28.7125,C,First,woman,False,C,Cherbourg,no,True
297,0,1,female,2.0,1,2,151.5500,S,First,child,False,C,Southampton,no,False
498,0,1,female,25.0,1,2,151.5500,S,First,woman,False,C,Southampton,no,False

In [57]:
df.iloc[np.where(df['Age']==80)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

In [58]:
df1[df1['sex']=='male']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
883,0,2,male,28.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [59]:
df1[df1['sex']=='female']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [60]:
df.loc[(df['Sex']=='male') & (df['Pclass']==1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [61]:
df.loc[np.where((df['Sex']=='male')&(df['Survived']==1))]
#number of males survived titanic using iloc

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
838,839,1,3,"Chip, Mr. Chang",male,32.0,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [62]:
df1.loc[(df1['sex']=='female') | (df1['age']<38)]  # either or

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [63]:
df1['age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [64]:
df1.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [65]:
df1.sex.unique()

array(['male', 'female'], dtype=object)

In [66]:
df1['sex'].unique()

array(['male', 'female'], dtype=object)

In [67]:
df1['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [68]:
df1.embarked.value_counts() # Values of each category

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [69]:
df1.sort_values('fare')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True
413,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
481,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
302,0,3,male,19.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
341,1,1,female,24.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True

In [70]:
df1.sort_values(['fare','sex'],ascending=False) #descending

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
438,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
674,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
732,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True
815,0,1,male,NaN,0,0,0.0000,S,First,man,True,B,Southampton,no,True
822,0,1,male,38.0,0,0,0.0000,S,First,man,True,NaN,Southampton,no,True

In [71]:
import seaborn as sns

In [72]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [73]:
a = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'name': ['Alice', 'Bob', 'Charlie', 'David']
})

b= pd.DataFrame({
    'id': [3, 4, 5, 6],
    'age': [23, 34, 45, 29]
})

In [74]:
a

   id     name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David

In [75]:
b

   id  age
0   3   23
1   4   34
2   5   45
3   6   29

In [76]:
concat=pd.concat([a,b]) # concat the 2 data frames ,1st dataframe upper, below 2nd data frame
concat                     # column doesn't matches means it will shows nan

   id     name   age
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie   NaN
3   4    David   NaN
0   3      NaN  23.0
1   4      NaN  34.0
2   5      NaN  45.0
3   6      NaN  29.0

In [77]:
pd.concat([a,b],ignore_index=True)

   id     name   age
0   1    Alice   NaN
1   2      Bob   NaN
2   3  Charlie   NaN
3   4    David   NaN
4   3      NaN  23.0
5   4      NaN  34.0
6   5      NaN  45.0
7   6      NaN  29.0

In [78]:
concat1=pd.concat([a,b],axis=1) #side by side matching index
concat1

   id     name  id  age
0   1    Alice   3   23
1   2      Bob   4   34
2   3  Charlie   5   45
3   4    David   6   29

In [ ]:
# append() will concat the only 2 frame
# concat() can take the more than 2 dataframe
# join -- it will join the data frame

In [79]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 40]
}, index=[1, 2, 3, 4])

df2 = pd.DataFrame({
    'city': ['NYC', 'LA', 'Chicago', 'Houston'],
    'salary': [70000, 80000, 90000, 100000]
}, index=[2, 4, 5, 6])

In [80]:
df1

      name  age
1    Alice   25
2      Bob   30
3  Charlie   35
4    David   40

In [81]:
df2

      city  salary
2      NYC   70000
4       LA   80000
5  Chicago   90000
6  Houston  100000

In [82]:
df1.join(df2,how='right') # side by side on index basis

    name   age     city  salary
2    Bob  30.0      NYC   70000
4  David  40.0       LA   80000
5    NaN   NaN  Chicago   90000
6    NaN   NaN  Houston  100000

In [83]:
pd.merge(a,b,on='id',how='inner')

   id     name  age
0   3  Charlie   23
1   4    David   34

In [84]:
import seaborn as sns

In [85]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [86]:
tip=sns.load_dataset('tips')
tip.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [87]:
# min,max,sum total bill w.r.t each sex
pd.pivot_table(data=tip,index=['sex'],values=['total_bill'],aggfunc=['mean','max','min'])

C:\Users\DELL\AppData\Local\Temp\ipykernel_9488\549712280.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(data=tip,index=['sex'],values=['total_bill'],aggfunc=['mean','max','min'])
C:\Users\DELL\AppData\Local\Temp\ipykernel_9488\549712280.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(data=tip,index=['sex'],values=['total_bill'],aggfunc=['mean','max','min'])
C:\Users\DELL\AppData\Local\Temp\ipykernel_9488\549712280.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(data=tip,index=['sex'],values=['total_bill'],aggfunc=['mean','max','min'])

             mean        max        min
       total_bill total_bill total_bill
sex
Male    20.744076      50.81       7.25
Female  18.056897      44.30       3.07

In [88]:
pd.crosstab(
    tip['day'],
    tip['sex'],
    values=tip['total_bill'],
    aggfunc='mean')

sex        Male     Female
day
Thur  18.714667  16.715312
Fri   19.857000  14.145556
Sat   20.802542  19.680357
Sun   21.887241  19.872222

In [89]:
tip.groupby("day")["tip"].sum()

C:\Users\DELL\AppData\Local\Temp\ipykernel_9488\1975448201.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tip.groupby("day")["tip"].sum()

day
Thur    171.83
Fri      51.96
Sat     260.40
Sun     247.39
Name: tip, dtype: float64

In [90]:
group=tip.groupby(["day","smoker"])["tip"].sum()
group

C:\Users\DELL\AppData\Local\Temp\ipykernel_9488\871642382.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  group=tip.groupby(["day","smoker"])["tip"].sum()

day   smoker
Thur  Yes        51.51
      No        120.32
Fri   Yes        40.71
      No         11.25
Sat   Yes       120.77
      No        139.63
Sun   Yes        66.82
      No        180.57
Name: tip, dtype: float64

In [91]:
tip.duplicated(keep=False).head() # marks duplicates are True

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [92]:
tip.drop_duplicates() # it will drop the duplicates

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[243 rows x 7 columns]

In [93]:
# droping the rows
tip.drop(index=[1,2,3,4]).head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2

In [94]:
# droping the columns
tip.drop(columns='size')

     total_bill   tip     sex smoker   day    time
0         16.99  1.01  Female     No   Sun  Dinner
1         10.34  1.66    Male     No   Sun  Dinner
2         21.01  3.50    Male     No   Sun  Dinner
3         23.68  3.31    Male     No   Sun  Dinner
4         24.59  3.61  Female     No   Sun  Dinner
..          ...   ...     ...    ...   ...     ...
239       29.03  5.92    Male     No   Sat  Dinner
240       27.18  2.00  Female    Yes   Sat  Dinner
241       22.67  2.00    Male    Yes   Sat  Dinner
242       17.82  1.75    Male     No   Sat  Dinner
243       18.78  3.00  Female     No  Thur  Dinner

[244 rows x 6 columns]

In [95]:
# droping the columns
tip.drop(columns='sex',inplace=True) # inplace will delete the original dataset

In [96]:
tip

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [97]:
# droping null values 
tip.dropna()

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [98]:
# checking null values
tip.isnull()

     total_bill    tip  smoker    day   time   size
0         False  False   False  False  False  False
1         False  False   False  False  False  False
2         False  False   False  False  False  False
3         False  False   False  False  False  False
4         False  False   False  False  False  False
..          ...    ...     ...    ...    ...    ...
239       False  False   False  False  False  False
240       False  False   False  False  False  False
241       False  False   False  False  False  False
242       False  False   False  False  False  False
243       False  False   False  False  False  False

[244 rows x 6 columns]

In [99]:
tip.isnull().sum()

total_bill    0
tip           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [100]:
cd=sns.load_dataset('titanic')
cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [101]:
cd['survived']=cd.survived.astype('float64') # type needs to be specific

In [102]:
cd['survived']

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
      ...
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: survived, Length: 891, dtype: float64

In [103]:
cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    float64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(3), int64(3), object(5)
memory usage: 80.7+ KB

In [105]:
cd['fare']=pd.to_numeric(cd.fare,downcast='float')
cd['fare']

0       7.250000
1      71.283302
2       7.925000
3      53.099998
4       8.050000
         ...
886    13.000000
887    30.000000
888    23.450001
889    30.000000
890     7.750000
Name: fare, Length: 891, dtype: float32

In [106]:
cd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    float64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float32
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float32(1), float64(2), int64(3), object(5)
memory usage: 77.2+ KB